### PR TITLE
Fix multiline config and comments

### LINKED ISSUE #433: Add `,` and `#` support to multiline config
This config

```
> 1%,
last 2 versions
```

leads to `Unknown browser query ""`

https://browsersl.ist/?q=%3E+2%25%2C%2Clast+2+version

### PR DESCRIPTION
**Pull request by tatarianBarbarian**
Fixes #433 
- added processing for input on the server side, just like here:
https://github.com/browserslist/browserslist/blob/main/node.js#L285-L295
- tuned formatting. It will format multiline queries only if there are no comments

After these edits:
- users are able to use comments
- trailing commas aren't a problem
- multiline config just works

https://github.com/browserslist/browsersl.ist/assets/35267898/d46734ad-82e5-4bd0-821b-88febb0ca016

### CODE REVIEW

File: client/view/Form/loadBrowsers.js [hunk 1]
```diff
@@ -36,7 +36,7 @@ export async function loadBrowsers(query, region) {
 
     if (response.status === 500) {
       throw new ServerError(
-        `Server error. a class="Link" href="https://github.com/browserslist/browserl.ist">
+        `Server error. <a class="Link" href="https://github.com/browserslist/browserl.ist">
```
Comment (ai) [inline client/view/Form/loadBrowsers.js:39]: Should be in separated PR

File: pnpm-lock.yaml [hunk 2]
```diff
@@ -1,4 +1,4 @@
-lockfileVersion: '6.0'
+lockfileVersion: '6.1'
```
Comment (ai) [inline pnpm-lock.yaml:1]: This one too

File: server/lib/get-browsers.js [hunk 3]
```diff
@@ -13,9 +13,11 @@ let updated = statSync(join(ROOT, '../../../pnpm-lock.yaml')).mtime
 
 export async function getBrowsers(query, region) {
   let browsersByQuery = []
+  let preparedQuery
 
   try {
-    browsersByQuery = browserslist(query)
+    preparedQuery = prepareQuery(query)
```
Comment (ai) [inline server/lib/get-browsers.js:19]: Not sure that this line should be in `try`.

I dont see transformations in `prepareQuery()` which should be replaced to `Unknown browser query` error.

File: client/view/Form/loadBrowsers.js (hunk 1 above)
Comment (tatarianBarbarian) [reply client/view/Form/loadBrowsers.js]: Created one.

File: server/lib/get-browsers.js (hunk 3 above)
Comment (tatarianBarbarian) [reply server/lib/get-browsers.js]: Fair enough. Moved it out of the `try` block.
Not sure if I need to do the preparation somewhere before, i.e., on HTTP-handler, where the "raw" query is extracted from the URL.

File: client/view/Form/transformQuery.js [hunk 4]
```diff
@@ -12,7 +12,7 @@ export function transformQuery(rawQuery) {
     } catch {}
   }
 
-  if (query.includes('\n')) {
+  if (query.includes('\n') && !query.includes('#')) {
```
Comment (ai) [inline client/view/Form/transformQuery.js:15]: > tuned formatting. It will format multiline queries only if there are no comments

I am not sure that we need to tune formatting anymore.

We have it as a hack. Right now (on the example video) when you delete comment and website converts `,\n` to `,` (without a space even) it looks like a bug.

Let’s remove that old formatting tunning code.

File: server/lib/get-browsers.js [hunk 5]
```diff
@@ -11,15 +11,16 @@ let bv = importJSON('../node_modules/browserslist/package.json').version
 let cv = importJSON('../node_modules/caniuse-lite/package.json').version
 let updated = statSync(join(ROOT, '../../../pnpm-lock.yaml')).mtime
 
-export async function getBrowsers(query, region) {
+export async function getBrowsers(rawQuery, region) {
   let browsersByQuery = []
+  let preparedQuery = prepareQuery(rawQuery)
```
[the remark this answers is not in the document]
Comment (tatarianBarbarian) [reply server/lib/get-browsers.js:16]: Acceptable!

[the remark this answers is not in the document]
Comment (tatarianBarbarian) [reply server/lib/get-browsers.js]: Btw, it also seems correct to rename entities on the client side, too. 
What we treat as a `query` should be a `config`. Will help to avoid some confusion.

[the remark this answers is not in the document]
Comment (ai) [reply server/lib/get-browsers.js]: I like it. We can even change the API (but need to change docs, of course).

File: client/index.html [hunk 6]
```diff
@@ -1,440 +1,671 @@
...
-    <form data-id="form" class="Form">
-      <div class="Form_query">
-        <textarea id="form_query" name="query" cols="30" rows="5" required class="Form_textarea" data-id="form_textarea" placeholder="Write the Browserslist config here…"></textarea>
-        <label for="form_query" class="Form_placeholder">Write the Browserslist config here…<br>
-          For example
-          <a class="QueryLink"><code>defaults</code></a>,
-          <a class="QueryLink"><code>> 0.2% and not dead</code></a>
-        </label>
-        <p class="Form_loader">Loading…</p>
+  <head>
```
Comment (ai) [inline client/index.html:3]: Unexpected formatting changes here too

File: client/index.html [hunk 7]
```diff
@@ -44,7 +44,7 @@ <h1 class="Intro_title">
     <h2 class="Interactive_title">Check compatible browsers</h2>
     <form data-id="form" class="Form">
       <div class="Form_query">
-        <textarea id="form_query" name="query" cols="30" rows="5" required class="Form_textarea" data-id="form_textarea" placeholder="Write the Browserslist config here…"></textarea>
+        <textarea id="form_query" name="config" cols="30" rows="5" required class="Form_textarea" data-id="form_textarea" placeholder="Write the Browserslist config here…"></textarea>
```
Comment (ai) [inline client/index.html:47]: `form_query` → `form_config`

**Comment by ai** [comment]
I tried manually a few scenarios with PR and found unexpected behavior:

## Story 1

1. Open new page
2. Add `# comment` to config field

Result: Audience coverage: 0.00 %

Expected result: the same as for empty result or some `set query` error

## Story 2

1. Open new page
2. Type (type fast, but not copy) `chrome 29,\nchrome 28`

Result: website truncates config to `chrome 29,chrome 28` (not always, need to repeat a few times)

Expected result: no changes in input form

## Story 3

1. Open new page
2. Click on `"browserslist": [ …` button on the left
3. Click on the same button again

Result: `defaults and supports es6-module,maintained node versions` after first click, `"browserslist": [ "defaults and supports es6-module", "maintained node versions" ]` after second

Expected result: the same result on every click
